version: "3"
services:
  cache:
    image: redis
    container_name: project-cache
    ports:
      - "6379:6379"
    depends_on:
      - database
    networks:
      - backend

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: project-db
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=project
      - MYSQL_PASSWORD=secret

  api:
    build:
      context: ./web-api
    container_name: project-api
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - DB_DRIVER=mysql
      - DB_HOST=project-db
      - DB_USERNAME=project
      - DB_PASSWORD=secret
      - DB_NAME=project
    volumes:
      - ./web-api/src:/home/node/app/src
    command: "yarn dev"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - cache
      - database
    networks:
      - backend
      - frontend

  ui:
    build:
      context: ./web-ui
    container_name: project-ui
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - API_URL=project-api
    volumes:
      - ./web-ui/src:/home/node/app/src
    command: "yarn start"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - frontend

networks:
  backend:
  frontend:
